### ISSUE TITLE
Combine PipelineMode issue exists in version 0.87.0

### ISSUE THREAD

**Issue by shydhanya** [awslabs/aws-service-catalog-factory#286]
Version 0.87.0 resolved GenerateLaunchConstraint Issue in Factory pipeline. Thankyou!

However, PipelineMode: combined is still not working -
# Folder Structure: 
![image](https://user-images.githubusercontent.com/37020616/187783218-8acc8926-e17f-45da-a3c9-d68aacf0df02.png)

# Product Template: 
![image](https://user-images.githubusercontent.com/37020616/187783534-1c0f8399-0b1d-42d6-abf6-a508dc1bf141.png)

# Expected results
Create a single product pipeline for multiple versions of the product

# Actual results
Created multiple product pipelines per version + a combined product pipeline. 

# Pipeline Screenshot
<img width="1482" alt="image" src="https://user-images.githubusercontent.com/37020616/187782765-ad66bfb9-29f8-40e1-bab1-2ea88ea46508.png">

# Combined product pipeline failed in Package Stage with error - 
<img width="2185" alt="image" src="https://user-images.githubusercontent.com/37020616/187782554-efc0201a-2c27-4059-8f9c-77bd74df55ee.png">

**Comment by shydhanya** [comment]
### Discoveries:
When PipelineMode: **combined** https://github.com/awslabs/aws-service-catalog-factory/blob/master/servicecatalog_factory/commands/portfolios.py#L207 executes and create x2 split pipelines and a combined pipeline
When PipelineMode: **split** - combined mode ran
When PipelineMode: **was not set**  https://github.com/awslabs/aws-service-catalog-factory/blob/master/servicecatalog_factory/commands/portfolios.py#L207 executes and create x2 split pipelines and a combined pipeline ran
### Other Observations :
It looks like the flow runs though the portfolio files and then the new product type when using the attached code sample
[ServiceCatalogFactory.zip](https://github.com/awslabs/aws-service-catalog-factory/files/9576975/ServiceCatalogFactory.zip)

### Linked to similar issue #291

**Comment by robbrad** [comment]
Looks like the duplication is caused because

https://github.com/awslabs/aws-service-catalog-factory/blob/master/servicecatalog_factory/commands/generate.py#L102

Is missing "Portfolios" from the path

The flow of the tooling builds a new portfolio file from the external referenced products. However if they are not removed as part of the refactor then they are read twice

Changes needed:

external_portfolio_definition_path = f"{p}/portfolios/{p_name}/{portfolio.get('DisplayName', portfolio.get('PortfolioName'))}"

To

external_portfolio_definition_path = f"{p}/portfolios/{p_name}/Portfolios/{portfolio.get('DisplayName', portfolio.get('PortfolioName'))}"

This should fix the issue

**Comment by eamonnfaherty** [comment]
this is resolved in https://github.com/awslabs/aws-service-catalog-factory/releases/tag/0.89.0
