### ISSUE TITLE
Simple portfolio failed with "Product not found" exception in product deployment stage  in version 0.87.0

### ISSUE THREAD

**Issue by shydhanya** [awslabs/aws-service-catalog-factory#287]
Framework is updated to latest version 0.87 released today. 
Generate Launch Constraint issue is resolved. 

# Folder Structure
![image](https://user-images.githubusercontent.com/37020616/187793527-4bf2b0b3-ad01-459e-bcc7-b18f8ca5698c.png)

# Product Template
![image](https://user-images.githubusercontent.com/37020616/187793639-a988d75e-de61-4e8d-b826-cb21d5cddd5a.png)

# Expected results
Create a product pipeline for v1

# Actual results
Product pipeline failed with product not found exception in **Deploy** stage.
<img width="1006" alt="image" src="https://user-images.githubusercontent.com/37020616/187793717-12b0ba63-efc7-4d99-81c9-c4824ab4cee7.png">

<img width="1148" alt="image" src="https://user-images.githubusercontent.com/37020616/187793750-731a5c39-bbeb-4d11-bc03-41073fc0d320.png">

# Observation 
1. This deployment error didn't occur in portfolio folder structure 
/portfolios/demo/Portfolios/central-it-team-portfolio/Products/account-vending-account-creation/Versions/
2. Product pipeline name would not start with products-- for PipelineMode: split

**Comment by robbrad** [comment]
Looks like the duplication is caused because 

https://github.com/awslabs/aws-service-catalog-factory/blob/master/servicecatalog_factory/commands/generate.py#L102

Is missing "Portfolios" from the path

The flow of the tooling builds a new portfolio file from the external referenced products. However if they are not removed as part of the refactor then they are read twice

Changes needed:

`external_portfolio_definition_path = f"{p}/portfolios/{p_name}/{portfolio.get('DisplayName', portfolio.get('PortfolioName'))}"
`

To

`external_portfolio_definition_path = f"{p}/portfolios/{p_name}/Portfolios/{portfolio.get('DisplayName', portfolio.get('PortfolioName'))}"
`

This should fix the issue

**Comment by xor007** [comment]
I had the same issue and it seems to me that it will always happen initially as the product does not exist initially. 

**It happens even while forllowing the workshop as is**

I had to change line 117 of cloud_formation_service_catalog_deploy_action.py from:

`product_details = servicecatalog.describe_product_as_admin(Name=product)`

to:
`        try:
            product_details = servicecatalog.describe_product_as_admin(Name=product)
        except Exception as e:
            print(f'Exception: {e}\n creating product as it does not exist')
            product_details = servicecatalog.create_product(
                Name=product,
                Owner='could-engineering',
                ProductType='CLOUD_FORMATION_TEMPLATE',
                ProvisioningArtifactParameters={
                    "Info": {"LoadTemplateFromURL": template_url}, 'Type': 'CLOUD_FORMATION_TEMPLATE'},
                Tags=[{'Key': 'OWNER','Value': 'NotAnOwner'}])`

To get it to work.

**Comment by robbrad** [comment]
@shydhanya - I think the "--" is intentional 

see : https://github.com/awslabs/aws-service-catalog-factory/blob/master/servicecatalog_factory/workflow/generic/create_generic_version_pipeline_task.py#L116,L119

**Comment by eamonnfaherty** [comment]
This should be resolved in version 0.89.0

If you see it still please re-raise.
