### ISSUE TITLE
Renaming a portfolio does not create new products

### ISSUE THREAD

**Issue by eamonnfaherty** [awslabs/aws-service-catalog-factory#41]

**Comment by sara-h-chen** [comment]
#### Issue description
When renaming a portfolio in the manifest file, products do not get moved into the new portfolio unless they are deleted and recreated, even if they are removed from the old portfolio.

#### Steps to reproduce the issue
1.  Deploy a portfolio containing products with `old_name`.
2. Remove the products from `old_name` and delete the `old_name` portfolio.
3. Rename `old_name` to `new_name`.
4. Run Service Catalog Puppet.

#### What's the expected result?
The products would appear in the `new_name` portfolio.

#### What's the actual result?
The products re-appear in the `old_name` portfolio and will not be placed in the `new_name` portfolio until they are completely deleted, including their stacks.

#### Additional details
This issue may be caused by the fact that products are only associated to portfolios at creation time. Hence, if the products are not being created for the first time, their associations to portfolios do not get updated.

**Comment by eamonnfaherty** [comment]
This is fixed in 0.1.34
